wet-boew/cdts-sgdc

Gruntfile.coffee
added cdts folder to hold assets
Related to https://github.com/wet-boew/wet-boew/commit/9b32cfb86ddbae692f29a22386baefbfdfb954b2#diff-a35864fcc4749a3b904641b4be9feacf
=> Create package.json file for cdn repo

.travis.yml, Gruntfile.coffee, package.json
add the release bash script to the deploy repos
=> remove the deploy release in the build

Gruntfile.coffee
deploying to https://github.com/wet-boew/cdts-sgdc-releases/
=> take two on deploy with Travis

Gruntfile.coffee
=> change release folder from version number to tag

Untitled-1.js, _src/html/gcintranet-en.html, _src/html/gcintranet-fr.html, _src/html/gcweb-en.html, _src/html/gcweb-fr.html, _src/html/index-fr.html, _src/html/index.html, _src/soy/gcintranet/en/gcintranet-en.soy, _src/soy/gcintranet/fr/gcintranet-fr.soy, _src/soy/gcweb/en/gcweb-en.soy, _src/soy/gcweb/fr/gcweb-fr.soy
add variable to set own path
related #1
=> fixing path

package-lock.json, package.json
- Add explicit coffeescript for newer grunt
- Bump all outdated grunt plug-ins
=> chore: Upgrade all devDependencies

public/gcintranet/ajax/sitemenu-eng.html, public/gcintranet/ajax/sitemenu-fra.html, public/gcintranet/samples/global-nav-menu-fr.html, public/gcweb/samples/breadcrumbs-en.html, public/gcweb/samples/breadcrumbs-fr.html
Was tried to run Prettier to see what it would output, and it choked on a few of these un-opened tags
=> fix: HTML parsing issues

src/gcweb/top.ejs, test/specs/top.js
=> Removing abbr element from breadcrumbs

src/gcintranet/serverTop.ejs, src/gcweb/serverTop.ejs
=> 80 remove link from error page fip

src/gcintranet/appTop.ejs, src/gcintranet/top.ejs, src/gcintranet/wet-messages.en.json, src/gcintranet/wet-messages.fr.json
=> 129 Add nav elements and aria labels in top/appTop

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml, .gitignore
=> Adding CodeQL pipeline

public/gcintranet/samples/exiturl-en.html, public/gcintranet/samples/exiturl-fr.html, public/gcweb/samples/exiturl-en.html, public/gcweb/samples/exiturl-fr.html, test/html/gcintranet/exiturl-en.html, test/html/gcintranet/exiturl-fr.html, test/html/gcweb/exiturl-en.html, test/html/gcweb/exiturl-fr.html
=> Update exiturl pages

CHANGELOG.md
=> Updating changelog for v4.0.44

package.json, public/gcintranet/cdtsfixes.css, test/pageobjects/appFooter.page.js
=> Fixing responsive design of sign in button

src/gcweb/top.ejs
=> 357 Fix comment in the breadcrumb section

public/gcweb/samples/home-en.html, public/gcweb/samples/home-fr.html
=> Fixing broken link

src/gcintranet/wet-header.js, src/gcweb/wet-header.js
=> Replacing String.startsWith calls with alternative compatible with IE11

.github/workflows/testlinks.yml
It'll be tested once merged I guess....
=> 452 testlinks no dependabot

public/gcintranet/samples/adobe-analytics-en.html, public/gcintranet/samples/adobe-analytics-fr.html, public/gcintranet/samples/index-fr.html, public/gcintranet/samples/index.html, public/gcweb/samples/adobe-analytics-en.html, public/gcweb/samples/adobe-analytics-fr.html, src/gcintranet/refFooter.ejs, src/gcintranet/refTop.ejs, test/specs/refTop.js
Will be in Draft mode until #443 gets merged.
=> Adding analytics for GCIntranet

CHANGELOG-fr.md
Identified here: https://github.com/cenw-wscoe/sgdc-cdts/issues/30
=> will be used as a reference in cdts github pages

TestLinks.js, public/gcintranet/samples/nodoc-write-en.html, public/gcintranet/samples/nodoc-write-fr.html, public/gcweb/samples/nodoc-write-en.html, public/gcweb/samples/nodoc-write-fr.html
Fixes https://github.com/wet-boew/cdts-sgdc/actions/runs/5111454518/jobs/9190564873
=> Fixing links and updating regex

TestLinks.js
Finally got a working pipeline with these changes.
@j-paquette When merging please squash the commits because it's not worth including all my attempts in history.
=> Fix testlinks

public/gcweb/samples/local-test-en.html, public/gcweb/samples/local-test-fr.html
When deploying CDTS in MWS, I found out that we were not testing the local server instance but it was always linking to the version published on production.
With this local test version, we will be able to quickly test a sample page of CDTS in our lower and in various environment where it do use that local instance.
=> gcweb - Add a sample which use local cdts instance

test/pageobjects/appTop.page.js, test/specs/appTop.js
issues found in appTop unit tests, while working on another PR.
=> adding fixes to appTop tests

src/gcintranet/appFooter.ejs, src/gcintranet/footer.ejs
Cherry picked: https://github.com/wet-boew/cdts-sgdc/commit/7119495de363e22a159908368ab5cb7a4c7b56fd
=> Adding missing alt text

test/specs/exitScript.js
This will fix timeout errors with exitScript tests.
=> fixes timeouts
